<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="app/views/css/style.css">
    <link rel="fonts" href="app/views/css/fonts.css">
    <title>Login</title>
</head>
<body>
    <main>
        <div class="center-login">
            <div class="card-login">
                <h1>LOGIN</h1>
                <form id="login-form" action="processaLogin.php" method="POST">
                    <div class="textfield">
                        <label for="usuario">Usuário</label>
                        <input type="text" name="usuario" placeholder="Usuário">
                    </div>
                    <div class="textfield">
                        <label for="senha">Senha</label>
                        <input type="password" name="senha" placeholder="Senha">
                    </div>
                        <button form="login-form" type="submit" class="btn-login">Login</button>
                </form>
            </div>
        </div>
    </main>
</body>
</html>
